### ISSUE TITLE
PlatformIO Library manager fails when updating libraries

### ISSUE THREAD

**Issue by luebbe** [euphi/HomieNodeCollection#3]
Hi, I'm trying to use your homie node collection in one of my projects. When I add it to the lib_deps in platformio.ini:

`lib_deps =
  https://github.com/euphi/HomieNodeCollection.git`

and compile, PlatformIO updates all libraries, but fails on the ESP8266_SSD1306 library. The error message is:

`Cloning into 'D:\Projekte\PlatformIO\Homie - Display\.piolibdeps\_tmp_installing-qdp7ot-package'...
warning: Could not find remote branch v2.0.0-beta.1 to clone.
fatal: Remote branch v2.0.0-beta.1 not found in upstream origin`

Exactly this branch is mentioned in library.json. When I replace the `#v2.0.0-beta.1` with `#master`, the library manager updates correctly.

**Comment by euphi** [comment]
Fixed with fffd2cc90b344388de0d69ee16d56aa05925bf1d and 51f7b74f3599fea48d1e91c8bee8137f047a9233 - these are already available at platformio.

(Note: There is another compiler failure due to change in Homie - this is fixed with latest commits, it will take some hours until these commits are propagated to PlatformIO.)
